FROM golang:1.17-buster

COPY . /workdir
WORKDIR /workdir

RUN apt update && apt install net-tools nano iproute2 php-cli -y && go build .

ENTRYPOINT ["/bin/bash"]
CMD ["-c", "cd __test__ && php -S 0.0.0.0:80"]